import { RiHome7Fill, RiFoldersFill, RiLockPasswordLine, RiLockPasswordFill } from "react-icons/ri";
import { BsGearFill, BsFillMoonFill, BsFillSunFill, BsFillBookmarkFill, BsImageFill, BsArrowDown } from "react-icons/bs";
import { FaShieldAlt, FaHashtag } from "react-icons/fa";
import { FiLogOut } from "react-icons/fi";
import { AiOutlinePlus } from "react-icons/ai";
import { BiSearchAlt, BiEditAlt, BiTrash, BiRename } from "react-icons/bi";
import { MdMenuOpen, MdMenu, MdOutlineCreateNewFolder, MdTopic, MdOutlineTopic, MdAlternateEmail } from "react-icons/md";
import { IoIosArrowForward, IoIosCloseCircle, IoMdMore, IoIosArrowBack } from "react-icons/io";
import { HiUsers } from "react-icons/hi";
import { ImStatsBars } from "react-icons/im";

export const homeIcon = <RiHome7Fill/>;
export const gearIcon = <BsGearFill/>;
export const shieldIcon = <FaShieldAlt/>;
export const logoutIcon = <FiLogOut/>;
export const moonIcon = <BsFillMoonFill/>;
export const sunIcon = <BsFillSunFill/>;
export const plusIcon = <AiOutlinePlus/>;
export const searchIcon = <BiSearchAlt/>;
export const menuOpenIcon = <MdMenuOpen/>;
export const menuIcon = <MdMenu/>;
export const bookmarkIcon = <BsFillBookmarkFill/>;
export const rightAngleIcon = <IoIosArrowForward/>;
export const leftAngleIcon = <IoIosArrowBack/>;
export const hashIcon = <FaHashtag/>;
export const folderPlusIcon = <MdOutlineCreateNewFolder/>;
export const usersIcon = <HiUsers/>;
export const foldersIcon = <RiFoldersFill/>;
export const statsIcon = <ImStatsBars/>;
export const themeIcon = <MdTopic/>;
export const subThemeIcon = <MdOutlineTopic/>;
export const editIcon = <BiEditAlt/>;
export const trashIcon = <BiTrash/>;
export const nameIcon = <BiRename/>;
export const arrobaIcon = <MdAlternateEmail/>;
export const passwordIcon = <RiLockPasswordLine/>;
export const confirmPasswordIcon = <RiLockPasswordFill/>;
export const imageIcon = <BsImageFill/>;
export const closeIcon = <IoIosCloseCircle/>;
export const moreIcon = <IoMdMore/>;
export const arrowDownIcon = <BsArrowDown/>;